config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :equipment
  root to: 'dashboard#index'
  get 'dashboard/statistic'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/equipment.rb
class Equipment
  include Mongoid::Document
  field :name, type: String
  field :ip, type: String
  field :status, type: String
  field :description, type: String
  
  embeds_many :equipment_histories, validate: true
  belongs_to :room
  
  def make_history(new_status,tmp_resp)
    self.update(:status=>new_status)
    EquipmentHistory.create(:equipment_id=>self.id,:status=>new_status, :room_id=>self.room_id, :response_time=>tmp_resp, :created_at=>DateTime.now)
  end
end

app/models/equipment_history.rb
class EquipmentHistory
  include Mongoid::Document
  field :status, type: String
  field :response_time, type: Float
  field :create_at, type: DateTime
  
  embedded_in :equipment
end

app/models/protocol.rb
class Protocol
  include Mongoid::Document
  field :name, type: String
end

app/models/room.rb
class Room
  include Mongoid::Document
  field :name, type: String
  field :number, type: String
  field :floor, type: String
  
  has_many :equipments
  
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  
  layout :layout

  private

  def layout
    # only turn it off for login pages:
    is_a?(Devise::SessionsController) ? false : "application"
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    redirect_to equipment_index_path
  end
  def statistic
    
  end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]

  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
  end

  # GET /equipment/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
        format.json { render :show, status: :created, location: @equipment }
      else
        format.html { render :new }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipment_index_url, notice: 'Equipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipment_params
      params.require(:equipment).permit(:name, :ip, :status, :description)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :number, :floor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current?(path)
        current_page?(path) ? "active" : ""
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/equipment/_form.html.erb
<%= form_for(equipment) do |f| %>
  <% if equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

      <ul>
      <% equipment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :ip %>
    <%= f.text_field :ip %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipment/edit.html.erb
<h1>Editing Equipment</h1>

<%= render 'form', equipment: @equipment %>

<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>

app/views/equipment/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Equipment</h1>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Grade de equipamentos</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-bar-chart-o fa-fw"></i> Grade de equipamentos
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="row"> 
          <%- @equipment.each do |e| %>
            <%= link_to(e) do %>
              <div class="col-md-2"> 
                    <h1>
                      <span class="glyphicon glyphicon-off " aria-hidden="true">
                        <i class="fa fa-square fa-stack-2x"></i>
                        <i class="fa fa-desktop fa-stack-1x fa-inverse"></i>
                      </span>
                    </h1>
                <h3><%= e.name %></h3> 
                <% if !e.equipment_histories.last.nil? %>
                  <p><strong>Status: </strong><%= e.equipment_histories.last.status %></p>
                <% else %>
                  <p><strong>Status: </strong>Sem registro</p>
                <% end %>
                <p><strong>Tipo: </strong><%#= e.type.name if !e.type.nil? %></p>
              </div>
            <% end %>
          <% end %>
        </div>  
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
  </div>
</div>
<br>

<%= link_to 'New Equipment', new_equipment_path %>

app/views/equipment/new.html.erb
<h1>New Equipment</h1>

<%= render 'form', equipment: @equipment %>

<%= link_to 'Back', equipment_index_path %>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @equipment.name %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @equipment.ip %>
</p>

<p>
  <strong>Status:</strong>
  <%= @equipment.status %>
</p>

<p>
  <strong>Description:</strong>
  <%= @equipment.description %>
</p>

<%= link_to 'Edit', edit_equipment_path(@equipment) %> |
<%= link_to 'Back', equipment_index_path %>

app/views/layouts/application.html.erb
<script>
  $(document).ready(function(){
    $(".push_menu").click(function(){
         $(".wrapper").toggleClass("active");
    });
  });
</script>
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <title>SAMURAI</title>

  </head>

  <body>
    <div class="container">
    	<div class="row">
    		<div class="wrapper">
      	     <!-- sidebar menu -->
          	    <div class="side-bar">
                    <ul>
                        <li class="menu-head">
                            SAMURAI <a href="#" class="push_menu"><span class="glyphicon glyphicon-align-justify pull-right"></span></a>
                        </li>
                        <div class="menu">
                            <li>
                              <%= link_to dashboard_statistic_path, class: current?(dashboard_statistic_path) do %>
                                 Dashboard <span class="glyphicon glyphicon-dashboard pull-right"></span>
                              <% end %>
                            </li>
                            <li>
                              <%= link_to equipment_index_path, class: current?(equipment_index_path) do %>
                                Grade <span class="glyphicon glyphicon-th pull-right"></span>
                              <% end %>
                            </li>
                            <li>
                              <%= link_to new_equipment_path, class: current?(new_equipment_path) do %>
                                Novo equipamento <span class="glyphicon glyphicon-dashboard pull-right"></span>
                              <% end %>
                            </li>
                            <li>
                              <%= link_to rooms_path, class: current?(rooms_path) do %>
                                Salas <span class="glyphicon glyphicon-dashboard pull-right"></span>
                              <% end %>
                            </li>
                            <li>
                              <%= link_to new_room_path, class: current?(new_room_path) do %>
                                Nova sala <span class="glyphicon glyphicon-dashboard pull-right"></span>
                              <% end %>
                            </li>
                            <li>
                              <%= link_to destroy_user_session_path, :method=>'delete' do %>
                                 Sair <span class="glyphicons glyphicons-exit pull-right"></span>
                              <% end %>
                            </li>
                        </div>
                    </ul>
          	    </div>   
                <div class="content">
                    <div class="col-md-12">
                        <%= yield %>
                    </div>
                </div>
            </div>
          </div>
        </div>
        <!-- /sidebar menu -->
      </div>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :floor %>
    <%= f.text_field :floor %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Floor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.number %></td>
        <td><%= room.floor %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @room.number %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @room.floor %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>